name: green_dot
description: A new flutter plugin project.
version: 0.0.6
author: Origogi
homepage: origogi.github.io

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.17.0 <2.0.0"

dependencies:
  tuple: ^1.0.3
  line_icons: ^0.2.0
  google_fonts: ^1.1.1

  flutter:
    sdk: flutter


dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:
  assets:
    - images/
    - images/naver/

  plugin:
    platforms:
      some_platform:
        pluginClass: somePluginClass
